apiVersion: v1
kind: Deployment
metadata:
 name: pod
 labels:
     app: mynewapp

spec: 
   replicas: 2
   selector:
     matchLabels:
      app: mynewapp
   template:
     matadata:
       labels:
         app: mynewapp

      spec:
   containers:
     -name: c1
      image: httpd
      ports:
       - containerport: 80     
